<h1>Lista de Tarefas</h1>

<ul>
    <?php foreach ($tasks as $index => $task_) : ?>
        <li>
            <form action="tasks.php" method="POST" class="form-inline">
                <input type='hidden' name="_method" value='DELETE'>
                <input type="hidden" name="task[id]" value="<?= $index ?>">
                <input type="submit" value="Remover">
            </form>
            <span><?= $task_->getName(); ?></span>
        </li>
    <?php endforeach ?>
</ul>

<form action="tasks.php" method="POST" class="display-inline">

    <div class="form-group">
        <label for="task_name">Tarefa:</label>
        <input id="task_name" type="text" name="task[name]" class="<?= $task->errors('name') ? 'is-invalid' : '' ?>">
        <span class="invalid-feedback"><?= $task->errors('name') ?></span>
    </div>

    <input type="submit" value="Adicionar">
</form>