<h1>Lista de Tarefas</h1>

<ul>
    <?php foreach ($tasks as $_task) : ?>
        <li>
            <form action="/tasks" method="POST" class="form-inline">
                <input type='hidden' name="_method" value='DELETE'>
                <input type="hidden" name="task[id]" value="<?= $_task->getId() ?>">
                <input type="submit" value="Remover">
            </form>
            <span><a href="/tasks/<?= $_task->getId() ?>"> <?= $_task->getName(); ?></a></span>
        </li>
    <?php endforeach ?>
</ul>

<?php $simpleForm->for($task, '/tasks', 'POST', function ($form) use ($task) { ?>

    <?= $form->inputFor('name', 'Nome') ?>
    <?= $form->submit('Adicionar') ?>

<?php }) ?>