<h1><?= $task->getName() ?></h1>

<h2>Colaboradores</h2>

<?php $simpleForm->for($task_user, "/tasks/{$task->getId()}/collaborators", 'POST', function ($form) use ($users) { ?>

    <?= $form->selectFor(attribute: 'user_id', name: 'Colaborador', prompt: 'Selecione', collection: $users) ?>
    <?= $form->submit('Adicionar') ?>

<?php }) ?>

<table>
    <thead>
        <th>ID</th>
        <th>Nome</th>
    </thead>
    <tbody>
        <?php foreach ($task->collaborators()->all() as $collaborator) : ?>
            <tr>
                <td><?= $collaborator->getId() ?></td>
                <td><?= $collaborator->getName() ?></td>
                <td>
                    <form action="<?= "/tasks/{$task->getId()}/collaborators/{$collaborator->getId()}" ?>" method="POST" class="form-inline">
                        <input type='hidden' name="_method" value='DELETE'>
                        <input type="submit" value="Remover">
                    </form>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<hr>

<a href="/tasks">Todas Tarefas</a>